import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App1",
  description: "Generated by create next app",
};

const themeInitializerScript = `
(function(){
  ${setInitialColorMode.toString()};
  setInitialColorMode();
})()
`;

function setInitialColorMode() {
  function getInitialColorMode() {

    // 現在のPreference状態を確認する
    // matchMedia: メディアクエリで適用するJSを切り替える
    // prefers-color-scheme:ユーザーが要求したテーマカラーを検出するためにCSSが備えている機能
    // 端末の外観設定でdarkモードが設定されているかを参照する
    const preference = window.matchMedia("(prefers-color-scheme: dark)");
    const hasMediaQueryPreference = typeof preference.matches === "boolean";
    if (hasMediaQueryPreference) {
      if (preference.matches) {
        window.localStorage.setItem("theme", "dark");
        return "dark";
      }
    }

    // localstrageからカラーを取得
    const storePreferenceMode = window.localStorage.getItem("theme");
    const hasStorePreference = typeof storePreferenceMode == "string";
    if (hasStorePreference) {
      return storePreferenceMode;
    }

    // デフォルト
    return "light";
  }
  const currentColorMode = getInitialColorMode();
  if (currentColorMode == "dark") {
    document.documentElement.setAttribute("data-theme", "dark");
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <script
          dangerouslySetInnerHTML={{
            __html: themeInitializerScript,
          }}
        ></script>
        {children}
      </body>
    </html>
  );
}
